name: homework_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.7
  dio: ^5.7.0
  flutter_riverpod: ^2.5.1
  collection: ^1.18.0
  freezed: ^2.5.7
  flutter_dotenv: ^5.1.0
  go_router: ^14.2.8
  retrofit: ^4.4.1
  logger: ^2.4.0  # for logging purpose
  json_annotation: ^4.9.0
  multiple_result: ^5.1.0
  flutter_svg: ^2.0.10+1
  flutter_gen_runner: ^5.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  retrofit_generator: '>=8.0.0 <10.0.0' # for Dart 3.3 use ^9.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
